version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      REDIS_ADDR: "redis:6379"
      DB_ADDR: "postgres://postgres:magic@db:5432/urlshortener?sslmode=disable"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: magic
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

networks:
  default:
    name: default
    external: true
